apiVersion: v1
kind: Service
metadata:
  name: day-on-earth
  namespace: default
spec:
  selector:
    app: day-on-earth-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
